apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: space_themed_port
  description: |
    No description provided
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Meeranmk/space_themed_port
  links:
    - title: Repository
      url: https://github.com/Meeranmk/space_themed_port
spec:
  type: service
  lifecycle: production
  owner: user:Meeranmk
